### DISCUSSION TITLE
Can't access DVD

### DISCUSSION THREAD

**Discussion by ffeingol** [jlesage/docker-handbrake#302] [Q&A]
My docker compose file is as follows:

```
handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - "$USERDIR/handbrake:/config:rw"
      - "/media/video:/storage:ro"
      - "$USERDIR/handbrakewatch:/watch:rw"
      - "/media/video:/output:rw"
    environment:
      - TZ=$TZ
      - GROUP_ID=$PGID
      - USER_ID=$PUID
      - SUP_GROUP_IDS=24
    devices:
      - /dev/sr0
      - /dev/dvd
      - /dev/dri
    restart: unless-stopped
```

From the logs, /dev/sr0 is recognized.  The problem is when I navigate to /dev/ I only see folder and I don't see the sr0 or dvd drvice.  I confirmed they are physically there by entering the container.

Thanks!
