### DISCUSSION TITLE
image file not being copied

### DISCUSSION THREAD

**Discussion by vdrover** [jlesage/docker-handbrake#383] [Q&A]
The image is working well for me with this exception: non-video files are not being copied to the output folder. I was wondering if perhaps specifying the following variable is required for non-video files to be copied: `AUTOMATED_CONVERSION_NON_VIDEO_FILE_EXTENSIONS: jpg jpeg png webp`

My compose file is below.

```
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - npm_proxy
    devices:
      - /dev/snd
      - /dev/dri
    deploy:
      resources:
        limits:
          cpus: "8"
    ports:
      - "5800:5800"
      # - "5900:5900"
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      APP_NICENESS: -15
      AUTOMATED_CONVERSION_PRESET: "Matroska/H.265 MKV 1080p30"
      AUTOMATED_CONVERSION_FORMAT: MKV
      AUTOMATED_CONVERSION_KEEP_SOURCE: 0
      AUTOMATED_CONVERSION_OUTPUT_SUBDIR: SAME_AS_SRC
      AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: copy
      HANDBRAKE_GUI: 0
    volumes:
      - $DOCKERDIR/appdata/handbrake:/config:rw
      - $DATADIR/handbrake/storage:/storage:ro
      - $DATADIR/handbrake/watch:/watch:rw
      - $DATADIR/handbrake/output:/output:rw
```
