### DISCUSSION TITLE
"/output" is not a writable directory.

### DISCUSSION THREAD

**Discussion by DonGar** [jlesage/docker-handbrake#414] [Q&A]
Sounds like a permission problem, but, if I open a shell in the container, I can create and remove files and directories in the output folder without any issues at all. However, if I chmod the permissions on a folder they do not change (always appearing all permissive to the container). Could this make handbrake think it doesn't have sufficient permissions?

To open the shell for testing:
`docker exec -it --user app 5af974c75190 /bin/bash`

I'm running this container on an ubuntu server with the output directory NFS mounted from a file server.  For the RO /storage folder, this is working perfectly.

I'm used to NFS mounting into containers, and don't normally have issues with it.

**Comment by jlesage** [comment]
How did you mount the NFS share on the host?
Can you provide and example of ownership/permissions of the output folder: `docker exec <container name> ls -ld /output`

**Comment by DonGar** [comment]
I mounted from the docker compose file:

```
    volumes:
      - rack_in:/storage:ro
      - rack_out:/output:rw
volumes:
  rack_in:
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.10,ro
      device: :/volume1/video_conversion/Raw
  rack_out:
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.10
      device: :/volume1/video_conversion/output
```

And here are some example commands showing I can create both files and directories in output, delete them, and what their permissions are. Also showing that you can chmod without error, but that it has no effect on actual permissions.

5af974c75190:/tmp$ touch /output/file
5af974c75190:/tmp$ mkdir /output/dir
5af974c75190:/tmp$ chmod 700 /output/file
5af974c75190:/tmp$ ls -al /output
total 4
drwxrwxrwx 1 app  app    14 Jun  3 02:38 .
drwxr-xr-x 1 root root 4096 May 28 15:20 ..
drwxrwxrwx 1 app  app     0 Jun  3 02:38 dir
-rwxrwxrwx 1 app  app     0 Jun  3 02:38 file
5af974c75190:/tmp$ rm -rf /output/*
