### ISSUE TITLE
Internal Permission Errors.

### ISSUE THREAD

**Issue by kwm1800** [jlesage/docker-handbrake#110]
I've been trying different methods. Giving folders 777, re-deploying and trying to mount as automatically created volumes but I always get these errors.

```
(ghb:951): Gtk-WARNING **: 07:31:53.875: Attempting to read the recently used resources file at '/config/xdg/data/recently-used.xbel', but the parser failed: Failed to open file “/config/xdg/data/recently-used.xbel”: Permission denied.



(ghb:951): Gtk-WARNING **: 07:31:53.893: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.896: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied


GLib-GIO-Message: 07:31:53.901: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.



(ghb:951): Gtk-WARNING **: 07:31:53.904: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.942: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.945: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.951: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.972: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.974: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied



(ghb:951): Gtk-WARNING **: 07:31:53.982: Unable to open server bookmarks: Failed to open file “/config/xdg/config/gtk-3.0/servers”: Permission denied


mkdir: cannot create directory ‘/tmp/tmp.O6DzNf0YHv’: Permission denied


/run/s6/services/autovideoconverter/autovideoconverter: line 85: /tmp/tmp.O6DzNf0YHv//watch/hash: Permission denied


[autovideoconverter] Processing watch folder '/watch'...


/run/s6/services/autovideoconverter/autovideoconverter: line 337: /tmp/tmp.uS24oyLOUM: Permission denied


/run/s6/services/autovideoconverter/autovideoconverter: line 314: /tmp/tmp.uS24oyLOUM: Permission denied


[autovideoconverter] Watch folder '/watch' processing terminated.


mkdir: cannot create directory ‘/tmp/tmp.O6DzNf0YHv’: Permission denied
```

And the messages repeat over and over again.

Now, with these errors I can access GUI but nothing shows up on storage despite I put some files.... obviously it can't even initiate watch and tmp folders in the first place. I have no clue at this point after I see same errors with different configurations of the volumes.

**Comment by kwm1800** [comment]
Welp, I found the issue. It was umask got wrong number. I fixed the umask value and the issue is fixed.

**Comment by ovizii** [comment]
I know this is an old issue but it's the closest to my problem, so I thought I'd try my luck here first:

Here is my error which seems related to the watch folder. I don't use the watch function, so I don't really care but it would be better for me to quiet down or solve this problem so tis not flooding my logs.

```
handbrake   | [autovideoconverter] mkdir: cannot create directory ‘/tmp/tmp.rtWpm8hoR6’: Permission denied
handbrake   | [autovideoconverter] Processing watch folder '/watch'...
handbrake   | [autovideoconverter] Watch folder '/watch' processing terminated.
handbrake   | [autovideoconverter] /etc/services.d/autovideoconverter/run: line 89: /tmp/tmp.rtWpm8hoR6//watch/hash: Permission denied
```

since you mentioned umask, mine is set to 117 

I did a `docker exec -ti handbrake bash` followed by `ls -al /` and found that the /tmp folder is owned by root which explains why the user app cannot write to it.

```
ls -al /
...
drwxrwxrwt    6 root root    9 Nov  7 12:02 tmp
...
```

```
ls -al /tmp/
total 25
drwxrwxrwt  6 root root   9 Nov  7 12:02 .
drwxr-xr-x 25 root root  28 Nov  7 11:46 ..
-r--r--r--  1 app  app   11 Nov  7 11:46 .X0-lock
drwxrwxrwt  2 root root   3 Nov  7 11:46 .X11-unix
-r--r--r--  1 root root 236 Nov  7 11:46 .webdata.js
drw-r-----  2 app  app    2 Nov  7 11:46 hb.810
drwxr-xr-x  3 root root   3 Nov  7 11:46 run
drw-------  2 app  app    2 Nov  7 11:46 tmp.rtWpm8hoR6
srw-rw----  1 app  app    0 Nov  7 11:46 vnc.sock

```

Any ideas?

**Comment by jlesage** [comment]
This is strange, you should not have these errors.  More details about your container config (how it has been created) would be needed.
You could also try to set `AUTOMATED_CONVERSION=0`, which prevents the service from starting.

**Comment by ovizii** [comment]
> `AUTOMATED_CONVERSION=0`,

Thanks, your workaround worked and fixed my problem. Just in case, here is my docker-compose.yml

```
version: '2.4'
# https://github.com/jlesage/docker-handbrake
    handbrake:
        image: jlesage/handbrake:latest
        container_name: handbrake
        hostname: handbrake
        restart: "no"

        ports:
          - 5801:5800

        environment:
          - USER_ID=1000
          - GROUP_ID=1000
          - UMASK=117
          - DISPLAY_WIDTH=1920
          - DISPLAY_HEIGHT=1080
          - AUTOMATED_CONVERSION_KEEP_SOURCE=1
          - AUTOMATED_CONVERSION=0


        volumes:
          - /etc/timezone:/etc/timezone:ro
          - ./handbrake:/config
          - /sixer/tmp/handbrake:/storage
          - /sixer/tmp/handbrake/output:/output
          - /sixer/tmp/handbrake/watch:/watch
          - /sixer/tmp/downloads:/storage/downloads
          - /sixer/Movies:/storage/movies
          - /sixer/Series:/storage/series
        cpus: 4
        mem_limit: 4G

        networks:
            - multimedia

networks:
    multimedia:
        external: true
        name: multimedia
```
