### ISSUE TITLE
Handbrake is only using CPU (not Intel Quicksync)

### ISSUE THREAD

**Issue by caymann12** [jlesage/docker-handbrake#129]
Handbrake version = 1.3.2 (x86_64)

Using, Intel QSV, available as H264 and H265 on Handbrake Video Option

CPU is running at 100%
Average frame rate is 13fps......i guess Intel QSV is not used?

OS: Linux 

When i do, ls -l /dev/dri:
nobody:users card0
nobody:users renderD128

I have tried the same with chown to myself and still get 13fps and 100% cpu usage
jim:users card0
jim:users renderD128

Using Docker Handbrake container  "Created": "2020-05-27T01:54:41.929353465Z"
Command line for Docker>

/usr/bin/docker run -d \
--name=handbrake --restart=always --net=bridge -p 5800:5800 \
-e PUID=1000 -e PGID=100 -e TZ=America/New_York \
-v /sharedfolders/data/config/handbrake:/config:rw \
-v /sharedfolders/data/downloads/completed/movies:/watch:rw \
-v /sharedfolders/data/config/handbrake/storage:/storage:ro \
-v /sharedfolders/data/complete/movies:/output:rw \
--device=/dev/dri:/dev/dri jlesage/handbrake

CPU Info>
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
CPU(s):                4
Thread(s) per core:    2
Core(s) per socket:    2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 78
Model name:            Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
Stepping:              3
CPU MHz:               800.008
CPU max MHz:           3400.0000
CPU min MHz:           400.0000
BogoMIPS:              5616.00

Any pointers is appreciated.

**Comment by caymann12** [comment]
More from Log File....
Opening /watch/ABC.mkv...

[14:36:22] CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
[14:36:22]  - Intel microarchitecture Skylake
[14:36:22]  - logical processor count: 4

[14:36:22] Intel Quick Sync Video support: yes
[14:36:22]  - Intel Media SDK hardware: API 1.32 (minimum: 1.3)

[14:36:22]  - H.264 encoder: yes
[14:36:22]     - preferred implementation: hardware (any) via ANY
[14:36:22]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice

[14:36:22]  - H.265 encoder: yes (8bit: yes, 10bit: no)
[14:36:22]     - preferred implementation: hardware (any) via ANY
[14:36:22]     - capabilities (hardware):  bpyramid icq vsinfo opt1

**Comment by caymann12** [comment]
Here's the activity log :

[14:02:20] gtkgui: HandBrake 1.3.2 (2020052700) - Linux x86_64 - https://handbrake.fr
Cannot load libnvidia-encode.so.1

[14:02:20] hb_init: starting libhb thread
[14:02:20] hb_init: starting libhb thread
[14:02:20] hb_init: starting libhb thread

[14:02:29] CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
[14:02:29]  - Intel microarchitecture Skylake
[14:02:29]  - logical processor count: 4
[14:02:29] Intel Quick Sync Video support: no

[14:02:29] hb_scan: path=/output/ABC.mkv, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
disc.c:323: failed opening UDF image /output/ABC/ABC.mkv
disc.c:424: error opening file BDMV/index.bdmv
disc.c:424: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2585: nav_get_title_list(/output/ABC/ABC.mkv/) failed

[14:02:29] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.1
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[14:02:29] dvd: not a dvd - trying as a stream/file instead

**Comment by jlesage** [comment]
Is the first log the conversion log ?  Are you using the UI or the automatic video converter?  Do you have issue with both h.264 and h.265 ?

**Comment by caymann12** [comment]
I am using UI, the first log is conversion log. I have no issue with h264 or h265
I have discovered that the container automatically starts encoding in the background some random file inside  the tree of this watch folder without my involvement. 
For example: say the watch folder was - /sharedfolders/watch (and then multiple sub-folders called movies (followed by m1, m2,m3...), tvshows(followed by tv1,tv2,tv3,...), pictures(followed by p1,p2,p4,...), the docker container would go pick (at random) m2 or tv3 or whatever and start encoding using the Fast_1080p_30 template. And there was no way to stop it.
If i opened up a GUI based encoding, then we are encoding two streams simultaneously (but one stream is in the background without my knowledge and i don't know how to kill it). As such the CPU shows 100% at all times. I wonder how to stop automatic encoding.

As a workaround i pointed the watch folder to something empty. That stopped any background encoding. But there is probably a better way.

On a separate note, i read on various forums that the correct choice for hardware based encoding in a linux OS is "vaapi" when using Intel QSV. The choice of h264.qsv or h265.qsv is appropriate only under windows OS. I am using this docker container under linux OS (openmediavault4 NAS which uses debian). However i don't see "vaapi" as a choice. This is just something i observed.

**Comment by caymann12** [comment]
sorry, i hit the wrong button to close this, i meant to keep it open as an issue

**Comment by jlesage** [comment]
If you don't use the watch folder, you just have to not map `/watch`.

As for you other point, `vaapi` is the name of the QSV driver.  In HandBrake, the video encoders using QSV are clearly identified (e.g. `H.264 (Intel QSV)`).

**Comment by NickF123** [comment]
The Handbrake Docker works with QSV for me with H264, H265, I'm passing --device='/dev/dri' to the container. 

uname - a:

4.19.107-Unraid #1 SMP x86_64 Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz GenuineIntel GNU/Linux

**Comment by guillaumedsde** [comment]
Intel QSV h265 encoder also working here by passing here with this docker-compose file:
```yaml
version: '3'
services:
  handbrake:
    image: jlesage/handbrake:latest
    environment:
      USER_ID: "1000"
      GROUP_ID: "1000"
      SUP_GROUP_IDS: "44,109"
      AUTOMATED_CONVERSION_KEEP_SOURCE: "0"
      AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: copy
      AUTOMATED_CONVERSION_SOURCE_STABLE_TIME: "15"
      AUTOMATED_CONVERSION_FORMAT: mkv
      AUTOMATED_CONVERSION_PRESET: Matroska/H.265 MKV DVD
      AUTOMATED_CONVERSION_OUTPUT_SUBDIR: SAME_AS_SRC
      AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS: --all-audio --all-subtitles
    ports:
      - "5801:5800"
    volumes:
      - "${DOCKER_DATA}/handbrake:/config:rw"
      - "${DATA}/MakeMKV/output:/watch:rw"
      - "${DATA}/HandBrake/output:/output:rw"
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - /dev/dri:/dev/dri 
```
