### ISSUE TITLE
The web interface shows incorrectly when the container is behind a reverse-proxy

### ISSUE THREAD

**Issue by v-bulynkin** [jlesage/docker-handbrake#150]
I've made a test deployment with Wordrpess, Adminer for MariaDB and jlesage/handbrake, which published via Traefik 2.3.

The docker-compose file is:
```yaml
version: '3'

services:

  reverse-proxy:
    image: traefik
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: sql123
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`docker.domain.local`) && PathPrefix(`/adminer`)"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: sql123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    labels:
      - "traefik.http.routers.wordpress.rule=Host(`docker.domain.local`)"

  handbrake:
    image: jlesage/handbrake
    environment:
      TZ: Europe/Moscow
      CLEAN_TMP_DIR: 1
      AUTOMATED_CONVERSION_KEEP_SOURCE: 0
    volumes:
      - ~/proj1/handbrake/config:/config:rw
      - ~/proj1/handbrake/storage:/storage:ro
      - ~/proj1/handbrake/watch:/watch:rw
      - ~/proj1/handbrake/output:/output:rw
    labels:
      - traefik.http.routers.handbrake.rule=host(`docker.domain.local`) && PathPrefix(`/conv`)
      - traefik.http.middlewares.handbrake.stripprefix.prefixes=/conv
      - traefik.http.routers.handbrake.middlewares=handbrake

volumes:
    db_data: {}
    wp_data: {}
```

Wordpress and Adminer work correctly, but Handbrake shows its page incompletely:
![Screenshot_2020-09-29 HandBrake](https://user-images.githubusercontent.com/56349712/94656143-58d66780-0308-11eb-9592-aa6a45137bfb.png)

I asked on the traefik community a question about this behaviour and received [the following answer](https://community.traefik.io/t/web-page-behind-traefik-2-3-shows-partially/7958/2):
> If an application uses absolute references in asset links instead of relative and you strip prefix from url the application will end up not being able to load the assets because they are not where it thinks they are. If you want to host on the same domain but different prefix, there is not a whole lot you can do about that apart from asking for support for that use case from the application vendor.

If it's true, could you please make the container reverse proxy-compatible?
