### ISSUE TITLE
autovideoconverter/HandBrakeCLI not applying nice

### ISSUE THREAD

**Issue by spannerman79** [jlesage/docker-handbrake#206]
My docker-compose.yml

```
version: '3'
services:
  handbrake:
    image: jlesage/handbrake:latest
    cap_add:
      - SYS_NICE
    ports:
      - '5800:5800'
      - '5900:5900'
    volumes:
      - '/share/CACHEDEV1_DATA/docker_data/handbrake:/config:rw'
      - '/share/CACHEDEV1_DATA:/storage:ro'
      - '/share/CACHEDEV1_DATA/docker_data/handbrake/watch:/watch:rw'
      - '/share/CACHEDEV1_DATA/docker_data/handbrake/output:/output:rw'
    environment:
      - TZ=Australia/Sydney
      - VNC_PASSWORD=removed
      - USER_ID=0
      - GROUP_ID=0
      - SUP_GROUP_IDS=1000
      - KEEP_APP_RUNNING=1
      - APP_NICENESS=19
      - AUTOMATED_CONVERSION_PRESET=removed
      - AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=10
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0
```

As you can see by the docker compose, I have both added SYS_NICE & have the required env var defined, but yet when viewing `htop` I see the nice value of the auto conversion is zero as well as HandBrakeCLI which is spawned under and including `bash run s6/services/autovideoconverter/autovideoconverter`, which means it wasn't ran with a nice value defined.
