### ISSUE TITLE
Quick Sync without host driver

### ISSUE THREAD

**Issue by matteocedroni** [jlesage/docker-handbrake#215]
It would be possible to enable Quick Sync without driver installed on host?

For example,
I'm using Photoprism and Docker container installs drivers internally during init process:

```
environment:
    - PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"
    - PHOTOPRISM_INIT: "intel-graphics tensorflow-amd64-avx2"
...
devices:
    - "/dev/dri:/dev/dri"
```
