### ISSUE TITLE
Invalid preset "Personal/Test"

### ISSUE THREAD

**Issue by malordin** [jlesage/docker-handbrake#242]
Hello everyone, please help, I set up a custom preset, created a category "Personal" and named my preset "Test", here is my docker-compose:

```
version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
      - "/mnt/md0/HandBrake/storage:/storage:ro"
      - "/mnt/md0/HandBrake/watch:/watch:rw"
      - "/mnt/md0/HandBrake/output:/output:rw"
    environment:
      - USER_ID=33
      - GROUP_ID=33
      - AUTOMATED_CONVERSION_CHECK_INTERVAL=5
      - AUTOMATED_CONVERSION_PRESET="Personal/Test"
      - AUTOMATED_CONVERSION_FORMAT="mp4"
```

When I run the docker-compose up -d and look at the automatic conversion logs, I see this:

```
handbrake_1  | [autovideoconverter] Starting conversion of '/watch/123.mp4' (25b7df4d5ad98069427c8d1987f2bf09) using preset '"Personal/Test"'...
handbrake_1  | [autovideoconverter] 1 title(s) to process.
handbrake_1  | [autovideoconverter] Conversion failed.
handbrake_1  | [autovideoconverter] For more details about the failure, see /config/log/hb/conversion.log.
handbrake_1  | [autovideoconverter] Watch folder '/watch' processing terminated.
```

These are the logs he's asking for:

```
[11:49:47] hb_init: starting libhb thread
[11:49:47] thread 7f0465832b38 started ("libhb")
HandBrake 1.5.1 (2022062800) - Linux x86_64 - https://handbrake.fr
16 CPUs detected
Invalid preset "Personal/Test"
Valid presets are:
    General/
        Very Fast 1080p30
            Small H.264 video (up to 1080p30) and AAC stereo audio, in
            an MP4 container.
        Very Fast 720p30
            Small H.264 video (up to 720p30) and AAC stereo audio, in an
            MP4 container.
................................
...............................
 Personal/
        Test
            Test description
```

What is the problem and why can't I get it to work? Any advice or solution would be greatly appreciated, thanks!

**Comment by malordin** [comment]
Well, while I was writing what the problem was, I figured it out myself, I fixed the lines with Env, removing unnecessary quotation marks and it all worked:

```
version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
      - "/mnt/md0/HandBrake/storage:/storage:ro"
      - "/mnt/md0/HandBrake/watch:/watch:rw"
      - "/mnt/md0/HandBrake/output:/output:rw"
    environment:
      - USER_ID=33
      - GROUP_ID=33
      - AUTOMATED_CONVERSION_CHECK_INTERVAL=5
      - AUTOMATED_CONVERSION_PRESET=Personal/Test
      - AUTOMATED_CONVERSION_FORMAT=mp4
```
