### ISSUE TITLE
AUTOMATED_CONVERSION_PRESET Not finding custom information

### ISSUE THREAD

**Issue by ArthurMitchell42** [jlesage/docker-handbrake#257]
I've seen that a fix for this was pushed in 2020 but it seems I'm still having this issue,
The Docker YAML is:

```
version: '3.2' 
services: 
  handbrake: 
    image: jlesage/handbrake:latest  
    container_name: Handbrake 
    restart: unless-stopped  
    # always no  
    ports: 
      - "5800:5800" 
    volumes: 
      - "/volume3/docker/handbrake/config:/config:rw" 
      - "/volume3/docker/handbrake/storage:/storage:ro" 
      - "/volume3/docker/handbrake/c2_1080p30:/watch:rw"  
      - "/volume3/docker/handbrake/c2_1080_high:/watch2:rw" 
      - "/volume3/docker/handbrake/c2_720_high:/watch3:rw" 
      - "/volume3/docker/handbrake/c2_1080_med:/watch4:rw" 
      - "/volume3/docker/handbrake/c2_720_med:/watch5:rw"  
      - "/volume3/docker/handbrake/output:/output:rw"
    environment: 
      - USER_ID=1026 
      - GROUP_ID=100 
      - DISPLAY_WIDTH=1280 
      - DISPLAY_HEIGHT=768 
      - AUTOMATED_CONVERSION_PRESET='General/Very Fast 1080p30' 
      - AUTOMATED_CONVERSION_PRESET_2='arthur/Very Fast 1080 High'
      - AUTOMATED_CONVERSION_PRESET_3='arthur/Very Fast 720 High'
      - AUTOMATED_CONVERSION_PRESET_4='arthur/Very Fast 1080 Medium' 
      - AUTOMATED_CONVERSION_PRESET_5='arthur/Very Fast 720 Medium' 
```

And the conversion log file is giving me this:
```
------ CONVERSION OUTPUT Fri Mar 24 17:33:58 UTC 2023 -------
[17:33:58] Compile-time hardening features are enabled
[17:33:58] hb_qsv_make_adapters_list: MFXVideoCORE_QueryPlatform failed impl=0 err=-16
[17:33:58] qsv: is available on this system
Cannot load libnvidia-encode.so.1
[17:33:59] hb_init: starting libhb thread
[17:33:59] thread 7f754fb82b38 started ("libhb")
HandBrake 1.6.1 (2023030600) - Linux x86_64 - https://handbrake.fr
4 CPUs detected
Invalid preset 'arthur/Very Fast 720 Medium'
Valid presets are:
    General/
        Very Fast 2160p60 4K AV1
            AV1 video (up to 2160p60) and AAC stereo audio, in an MP4
            container.
        Very Fast 2160p60 4K HEVC
            H.265 video (up to 2160p60) and AAC stereo audio, in an MP4
            container.
        Very Fast 1080p30
            Small H.264 video (up to 1080p30) and AAC stereo audio, in
            an MP4 container.
........
    arthur/
        Very Fast 1080 High
            Small H.264 video (up to 1080p30) and AAC stereo audio, in
            an MP4 container.
        Very Fast 720 High
            Small H.264 video (up to 720p30) and AAC stereo audio, in an
            MP4 container.
        Very Fast 1080 Meduim
            Small H.264 video (up to 1080p30) and AAC stereo audio, in
            an MP4 container.
        Very Fast 720 Medium
            Small H.264 video (up to 720p30) and AAC stereo audio, in an
            MP4 container.
HandBrake has exited.

```
I've followed advice on the previous examples of this but so far no luck, any advice is most welcome.
Arthur
