### ISSUE TITLE
readme update for `AUTOMATED_CONVERSION_OUTPUT_DIR` overrides

### ISSUE THREAD

**Issue by vdrover** [jlesage/docker-handbrake#267]
In my testing with docker compose on Ubuntu 22, `AUTOMATED_CONVERSION_OUTPUT_DIR_2` was not respected unless `AUTOMATED_CONVERSION_OUTPUT_DIR` was defined. This surprised me as I was not trying to override the default `/output` defined in the volumes.

Additionally, including the `AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2` variable without first including `AUTOMATED_CONVERSION_OUTPUT_DIR_2` caused the application to crash/exit.

Probably I ran into these issues as I assumed the first output volume was a "default" and didn't need an override. 

In any case, here are what I think would be helpful additions to the existing docs (or perhaps a new section entitles "Multiple output folders"):
1. If needed, additional watch folders can be used: /output2, /output3, etc. Each additional folder should be defined in the volumes variables.
2. For each output folder (including the the first one, /output), explicitly define the variables for  `AUTOMATED_CONVERSION_OUTPUT_SUBDIR` and `AUTOMATED_CONVERSION_OUTPUT_DIR`. For example, if you have 3 output folders, include these 6 entries in the environment variables:
```
     AUTOMATED_CONVERSION_OUTPUT_DIR: /output
     AUTOMATED_CONVERSION_OUTPUT_SUBDIR: SAME_AS_SRC
     AUTOMATED_CONVERSION_OUTPUT_DIR_2: /output2
     AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2: SAME_AS_SRC
     AUTOMATED_CONVERSION_OUTPUT_DIR_3: /output3
     AUTOMATED_CONVERSION_OUTPUT_SUBDIR_3: SAME_AS_SRC
```
Also include these entries in the volume variables (adjusted for specific host file paths):
```
      - "home/username/handbrake/output:/output:rw"
      - "mnt/dvr/tv:/output2:rw"
      - "mnt/dvr/movies:/output3:rw"
```

Here is my complete compose file for context (customized for Emby live TV recording in this case).
```
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    ports:
      - "5800:5800"
    environment:
     USER_ID: $PUID
     GROUP_ID: $PGID
     TZ: $TZ
     APP_NICENESS: "19"
     AUTOMATED_CONVERSION: "1"
     AUTOMATED_CONVERSION_PRESET: "General/HQ 1080p30 Surround X265"
     AUTOMATED_CONVERSION_FORMAT: "mp4"
     AUTOMATED_CONVERSION_KEEP_SOURCE: "0"
     AUTOMATED_CONVERSION_VIDEO_FILE_EXTENSIONS: "ts"
     AUTOMATED_CONVERSION_NON_VIDEO_FILE_EXTENSIONS: "nfo jpg png bif srt"
     AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: "copy"
     AUTOMATED_CONVERSION_OUTPUT_DIR: /output
     AUTOMATED_CONVERSION_OUTPUT_SUBDIR: SAME_AS_SRC
     AUTOMATED_CONVERSION_OUTPUT_DIR_2: /output2
     AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2: SAME_AS_SRC
     AUTOMATED_CONVERSION_OUTPUT_DIR_3: /output3
     AUTOMATED_CONVERSION_OUTPUT_SUBDIR_3: SAME_AS_SRC
    volumes:
      - "$DOCKERDIR/appdata/handbrake:/config:rw"
      - "$DATADIR/handbrake/storage:/storage:ro"
      - "home/username/handbrake/output:/output:rw"
      - "mnt/tv:/output2:rw"
      - "mnt/movies:/output3:rw"
      - "home/username/handbrake/watch:/watch:rw"
      - "mnt/dvr/shows:/watch2:rw"
      - "mnt/dvr/movies:/watch3:rw"
```
