### ISSUE TITLE
Example Docker-compose with environments

### ISSUE THREAD

**Issue by kevincaradant** [jlesage/docker-handbrake#63]
Hi

I try to use this image with docker-compose but even after to use the VNC GUI to create my preset and set it as environment. It doesn't seems to keep in mind my MKV format with AUTOMATIC WATCH. 

I try this:
```
version: '3'
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    restart: unless-stopped
    environment:
      - AUTOMATED_CONVERSION_PRESET=Very Fast 1080p30V2
    devices:
      - /dev/snd
      - /dev/dri
    ports:
      - 5803:5800
    volumes:
      - /docker/appdata/handbrake:/config:rw
      - /home/pc/Document/project/handbrake:/storage:ro
      - /media/pc/storage:/watch:rw
      - /media/pc/converted:/output:rw
```

In VNC I get that:
![image](https://user-images.githubusercontent.com/6093175/57316232-99bb5400-70f5-11e9-86d1-b89a941e523d.png)
And matroska(avformat) = mkv isn't it ?
With GUI, it's working, I have a MKV in output, but with Docker Automation, I have a MP4. I already executed docker-compose down and docker-compose up -d again, without success

So how can I have a MKV as output after the transcode of the episode when I use the AUTOMATIC MODE in Docker  :/

Edit:
In logs, it's seems to use the profile but it's wrong :/

```
[autovideoconverter] Starting conversion of '/watch/The Big Bang Theory S12E21 /The.Big.Bang.Theory.S12E21.mkv' (18a1d0c0dfebde) using preset 'Very Fast 1080p30V2'...
[autovideoconverter] 1 title(s) to process.
```

Thanks in advance

EDIT 2: OK my bad, sorry for that, I just understand that the AUTOMATED_CONVERSION_FORMAT is not only when you don't create a PRESET, it's useful in any case when I need to change the extension o the file.

I close the issue, it was almost obvious, maybe it should be notified in the readme finally :)
