### ISSUE TITLE
Server Disconnected

### ISSUE THREAD

**Issue by Tharic99** [jlesage/docker-handbrake#65]
I'm running your HandBrake and I noticed since late last week when I go to the :5800 web browser port, I get the overlay section at the top, but the actual HandBrake app doesn't start up. It just sits there with a **Server Disconnected (code: 1006)** red X error message on the top to the right of where it says HandBrake.

I've deleted my image a few times and pulled it down again, with no change at all. 

Here's the bottom contents of my log file though.

````
[services.d] starting openbox...
[openbox] starting...
[services.d] starting logmonitor...
[logmonitor] no file to monitor: disabling service...
[services.d] starting app...
[app] starting HandBrake...
[services.d] done.
(ghb:1056): GLib-GIO-CRITICAL **: 10:26:44.272: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
GLib-GIO-Message: 10:26:44.810: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
````

**Comment by jlesage** [comment]
Can you try to clear your browser cache?

**Comment by nicolass67** [comment]
Hello, 
I have the same issue 
The problem isn't at browser level, docker container stops quite immediately after start. 
I'm using the latest tag image. 
Attached is the content of the 'docker logs <containerid>' command. 
[log.txt](https://github.com/jlesage/docker-handbrake/files/3207042/log.txt)

Regards,

**Comment by nicolass67** [comment]
Hi, 

I tried some further tests. 
When using the HANDBRAKE_DEBUG=1 environment variable it gives nothing, in the handbrake log : 

`(null): create_builder_or_die()`

Then I looked on the Docker host machine, and there I saw this in the /var/log/messages : 

` kernel: [70329.600361] traps: ghb[29403] trap invalid opcode ip:7efe8b910ee5 sp:7ffc9c1640c0 error:0 in libmfxhw64.so.1.28[7efe8b909000+264000]`

Maybe a related with this lib ?

**Comment by jlesage** [comment]
Can you provide the full log?  Also, how did you created the container (what is your docker run command)?

**Comment by nicolass67** [comment]
It's the only on line in the logs for the container on the host machine. Rest is normal. 
Here is the docker compose I use 

```
version: '3'
services:
  handbrake:
    image: 'jlesage/handbrake:latest'
    network_mode: bridge
    ports:
      - "60080:5800"
    volumes:
      - config:/config
      - storage:/storage
      - watch:/watch
      - output:/output

volumes: 
  config: 
  storage: 
  watch: 
  output: 

From the preious errror message, maybe something is missing for the lib libmfxhw64.so. 


```
